---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: cluster-validation-pr{{ pull_request_number }}-{{ revision }}
  labels:
    appstudio.openshift.io/application: odh-gitops
    appstudio.openshift.io/component: cluster-validation
    pipelines.appstudio.openshift.io/type: test
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/on-comment: "^/validate-dependencies"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
spec:
  params:
    - name: git-url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
  taskRunTemplate:
    serviceAccountName: build-pipeline-cluster-validation
  pipelineSpec:
    params:
      - name: git-url
        type: string
      - name: revision
        type: string
    tasks:
      - name: provision-eaas-space
        taskRef:
          resolver: git
          params:
            - name: url
              value: https://github.com/konflux-ci/build-definitions.git
            - name: revision
              value: main
            - name: pathInRepo
              value: task/eaas-provision-space/0.1/eaas-provision-space.yaml
        params:
          - name: ownerName
            value: $(context.pipelineRun.name)
          - name: ownerUid
            value: $(context.pipelineRun.uid)

      - name: provision-cluster
        runAfter:
          - provision-eaas-space
        taskSpec:
          results:
            - name: clusterName
              value: $(steps.create-cluster.results.clusterName)
          volumes:
            - name: credentials
              emptyDir: {}
          steps:
            - name: create-cluster
              ref:
                resolver: git
                params:
                  - name: url
                    value: https://github.com/konflux-ci/build-definitions.git
                  - name: revision
                    value: main
                  - name: pathInRepo
                    value: stepactions/eaas-create-ephemeral-cluster-hypershift-aws/0.1/eaas-create-ephemeral-cluster-hypershift-aws.yaml
              params:
                - name: eaasSpaceSecretRef
                  value: $(tasks.provision-eaas-space.results.secretRef)
                - name: version
                  value: "4.19.0"
                - name: instanceType
                  value: "m5.xlarge"

            - name: get-kubeconfig
              ref:
                resolver: git
                params:
                  - name: url
                    value: https://github.com/konflux-ci/build-definitions.git
                  - name: revision
                    value: main
                  - name: pathInRepo
                    value: stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
              params:
                - name: eaasSpaceSecretRef
                  value: $(tasks.provision-eaas-space.results.secretRef)
                - name: clusterName
                  value: $(steps.create-cluster.results.clusterName)
                - name: credentials
                  value: credentials

      - name: deploy-and-verify-dependencies
        runAfter:
          - provision-cluster
        taskSpec:
          volumes:
            - name: credentials
              emptyDir: {}
            - name: workspace
              emptyDir: {}
          steps:
            - name: get-kubeconfig
              ref:
                resolver: git
                params:
                  - name: url
                    value: https://github.com/konflux-ci/build-definitions.git
                  - name: revision
                    value: main
                  - name: pathInRepo
                    value: stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
              params:
                - name: eaasSpaceSecretRef
                  value: $(tasks.provision-eaas-space.results.secretRef)
                - name: clusterName
                  value: $(tasks.provision-cluster.results.clusterName)
                - name: credentials
                  value: credentials

            - name: verify-cluster-and-clone
              image: quay.io/konflux-ci/appstudio-utils:latest
              workingDir: /workspace
              env:
                - name: KUBECONFIG
                  value: /credentials/$(steps.get-kubeconfig.results.kubeconfig)
              volumeMounts:
                - name: credentials
                  mountPath: /credentials
                - name: workspace
                  mountPath: /workspace
              script: |
                #!/bin/bash
                set -e

                echo "=== Verifying cluster access ==="
                oc version
                oc get nodes
                echo "✅ Cluster is accessible"

                echo ""
                echo "=== Cloning repository ==="
                git clone $(params.git-url) repo
                cd repo
                git checkout $(params.git-revision)
                echo "✅ Repository cloned"

            - name: apply-and-verify-dependencies
              image: quay.io/konflux-ci/appstudio-utils:latest
              workingDir: /workspace/repo
              env:
                - name: KUBECONFIG
                  value: /credentials/$(steps.get-kubeconfig.results.kubeconfig)
              volumeMounts:
                - name: credentials
                  mountPath: /credentials
                - name: workspace
                  mountPath: /workspace
              script: |
                #!/bin/bash
                set -e

                echo "=== Applying and verifying dependencies ==="
                make apply-and-verify-dependencies K8S_CLI=oc

                echo ""
                echo "✅ All dependencies applied and verified successfully!"
        params:
          - name: git-url
            value: $(params.git-url)
          - name: git-revision
            value: $(params.revision)
